CREATE TABLE CONTAINS (
    OrderID INT,
    BookID INT,
    Price DECIMAL(10, 2),
    Quantity INT,
    PRIMARY KEY (OrderID, BookID),
    FOREIGN KEY (OrderID) REFERENCES `ORDER`(OrderID),
    FOREIGN KEY (BookID) REFERENCES BOOK(BookID)
);
