CREATE TABLE WRITTEN_BY (
    AuthorID INT,
    BookID INT,
    PRIMARY KEY (AuthorID, BookID),
    FOREIGN KEY (AuthorID) REFERENCES AUTHOR(AuthorID),
    FOREIGN KEY (BookID) REFERENCES BOOK(BookID)
);
